import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Software Setup",
  description: "Generated by Baitul Hikmah Team",
};

const SoftwareSetup = ({ children }: IChildren) => <main>{children}</main>;

export default SoftwareSetup;
