import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Packages",
  description: "Generated by Baitul Hikmah Team",
};

const PackagesLayout = ({ children }: IChildren) => <main>{children}</main>;

export default PackagesLayout;
