import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | App Install",
  description: "Generated by Baitul Hikmah Team",
};

const AppInstallLayout = ({ children }: IChildren) => <>{children}</>;

export default AppInstallLayout;
