// import "@styles/globals.css";
import { Header } from "@/Components/Shared/Header";
import { IChildren } from "@/Interface";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Connect Desk",
  description: "Generated by Baitul Hikmah Team",
};

const RootLayout = ({ children }: IChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <Header />
      <main>{children}</main>
      {/* <Footer /> */}
    </body>
  </html>
);

export default RootLayout;
