import { Metadata } from "next";
import { Exo, Inter, Poppins } from "next/font/google";
import { FC } from "react";

import { IChildren } from "@/Interface";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });
const exo = Exo({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Connect Desk",
  description: "Generated by Baitul Hikmah Team",
};

const RootLayout: FC<IChildren> = ({ children }) => (
  <html lang="en">
    <body className={(poppins.className, exo.className, inter.className)}>
      {children}
    </body>
  </html>
);

export default RootLayout;
