import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | POS Inventory Software",
  description: "Generated by Baitul Hikmah Team",
};

const POSInventorySoftwareLayout = ({ children }: IChildren) => (
  <main>{children}</main>
);

export default POSInventorySoftwareLayout;
