import { IChildren } from "@Interface";

export const metadata = {
  title: "Connect Desk | Login Password",
  description: "Generated by Baitul Hikmah Team",
};

const LoginLayout = ({ children }: IChildren) => (
  <html lang="en">
    <body>
      <main>{children}</main>
    </body>
  </html>
);

export default LoginLayout;
