import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Forget Password",
  description: "Generated by Baitul Hikmah Team",
};

const ForgetPasswordLayout = ({ children }: IChildren) => (
  <main>{children}</main>
);

export default ForgetPasswordLayout;
