import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | FAQ",
  description: "Generated by Baitul Hikmah Team",
};

const FAQLayout = ({ children }: IChildren) => <main>{children}</main>;

export default FAQLayout;
