import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Confirm Password",
  description: "Generated by Baitul Hikmah Team",
};

const ConfirmPasswordLayout = ({ children }: IChildren) => (
  <main>{children}</main>
);

export default ConfirmPasswordLayout;
