import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Register",
  description: "Generated by Baitul Hikmah Team",
};

const RegisterLayout = ({ children }: IChildren) => <main>{children}</main>;

export default RegisterLayout;
