import { IChildren } from "@/Interface";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Connect Desk | Dashboard",
  description: "Generated by Baitul Hikmah Team",
};

const DashboardLayout = ({ children }: IChildren) => <main>{children}</main>;

export default DashboardLayout;
