import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Dashboard",
  description: "Generated by Baitul Hikmah Team",
};

const DashboardLayout = ({ children }: IChildren) => <main>{children}</main>;

export default DashboardLayout;
