import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Login",
  description: "Generated by Baitul Hikmah Team",
};

const LoginLayout = ({ children }: IChildren) => <main>{children}</main>;

export default LoginLayout;
