import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | OTP",
  description: "Generated by Baitul Hikmah Team",
};

const OTPLayout = ({ children }: IChildren) => <main>{children}</main>;

export default OTPLayout;
