import { Metadata } from "next";
import { Exo, Inter, Poppins } from "next/font/google";
import { FC } from "react";

import { dir } from "i18next";
import { languages } from "@/app/i18n/settings";
import { IChildrenWithIntl } from "@/Interface";

import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });
const exo = Exo({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: "Connect Desk",
  description: "Generated by Baitul Hikmah Team",
};

const RootLayout: FC<IChildrenWithIntl> = ({ children, params: { lng } }) => (
  <html lang={lng} dir={dir(lng)}>
    <body className={(poppins.className, exo.className, inter.className)}>
      {children}
    </body>
  </html>
);

export default RootLayout;
